### ISSUE TITLE
shortcut not working with parameters?

### ISSUE THREAD

**Issue by eparisio** [aziz/SublimeHyperClick#23]
hi, i have tested the shortcut f12 but it's not working unless i will override the default command with:

`{ "keys": ["f8"], "command": "hyper_click_jump" }`

how the **context** is set?
i see that it's only set in the annotator.py

**Comment by kalahooo** [comment]
Another problem. Shortcut doesn't work, but mouseclick on arrow works.

![screen shot 2017-08-30 at 19 07 38](https://user-images.githubusercontent.com/5232408/29882782-cfdb502c-8db6-11e7-80f0-6fc850cec6fd.png)

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "hyper_click_command in /Users/klh/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 34, in run
  File "hyper_click.path_resolver in /Users/klh/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 14, in __init__
  File "hyper_click.js_path_resolver in /Users/klh/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 25, in __init__
TypeError: 'NoneType' object is not iterable`

**Comment by eparisio** [comment]
@kalahooo yes i have opened an issue relative to the bug #21

**Comment by kud** [comment]
I'm not sure to understand but I did that:

```
  {
    "keys": ["alt+enter"],
    "command": "hyper_click_jump",
    "context": [{ "key": "hyper_click_jump_line", "operand": true }]
  },
```

and it works like a charm.

(but this issue is a bit old, maybe it's not releevant anymore?)

**Comment by braver** [comment]
> but this issue is a bit old, maybe it's not releevant anymore?

I've got the same feeling, it seems the issues were never cleaned up after work done on the plugin solved these issues.

**Comment by cristianl** [comment]
I could still reproduce this bug earlier this year, with `"annotations_enabled"` set to false. At least as of 2.0 this is gone.
