### ISSUE TITLE
NameError: global name 'scope_is_sass' is not defined

### ISSUE THREAD

**Issue by ildella** [aziz/SublimeHyperClick#79]
I recently switched to Sublime Text v4, currently using build 4093 on Ubuntu 20.10, Python 3.8.6

Since a few days I am always getting this error in the console logs:

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 944, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click_annotator.py", line 105, in on_activated_async
    self.on_selection_modified_async(view)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click_annotator.py", line 102, in on_selection_modified_async
    self.annotate(point, view)
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click_annotator.py", line 64, in annotate
    resolved_path = file_path.resolve()
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click/path_resolver.py", line 17, in resolve
    return self.resolver.resolve()
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click/generic_path_resolver.py", line 103, in resolve
    result = self.resolve_in_lookup_paths(self.str_path)
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click/generic_path_resolver.py", line 130, in resolve_in_lookup_paths
    result = self.resolve_relative_to_dir(target, path.join(self.current_root, lookup_path))
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click/generic_path_resolver.py", line 124, in resolve_relative_to_dir
    return self.resolve_as_file(combined) or self.resolve_as_directory(combined)
  File "/home/ildella/.config/sublime-text-3/Installed Packages/HyperClick.sublime-package/hyper_click/generic_path_resolver.py", line 215, in resolve_as_directory
    if scope_is_sass or scope_is_css:
NameError: global name 'scope_is_sass' is not defined
```

**Comment by jfcherng** [comment]
Probably fixed by https://github.com/aziz/SublimeHyperClick/pull/77/files#diff-0e0f678004a2c52fab4dfd441f71ebdebb5f1f313fe489f6d9b17463acd4ee2dL215 but that `2.3` release wasn't release deployed a few days ago.

**Comment by cristianl** [comment]
[2.3.0](https://github.com/aziz/SublimeHyperClick/releases/tag/2.3.0) is now available on Package Control.
