### ISSUE TITLE
'NoneType' object has no attribute 'folders'

### ISSUE THREAD

**Issue by SomeKittens** [aziz/SublimeHyperClick#9]
Vanilla install of HyperClick on SublimeText 3 v3126 via Package Control (OSX 10.12.1)

Full trace:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 425, in on_load
    attach_view(v)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 276, in attach_view
    check_view_event_listeners(view)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in check_view_event_listeners
    listeners.append(cls(view))
  File "hyper_click_annotator in /Users/rkoutnik/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 34, in __init__
AttributeError: 'NoneType' object has no attribute 'folders'
```

**Comment by aziz** [comment]
It this happening all the time or happened just once? 
I've seen it once or twice and it seems like a Sublime bug not providing the Window object at the time when plugin is initializing.

**Comment by SomeKittens** [comment]
It's happening all the time, I haven't gotten HyperClick to work yet.

**Comment by aziz** [comment]
I don't know why it's not working. could you give more information about sublime version, OS, etc.

**Comment by SomeKittens** [comment]
@aziz What more do you need that I didn't provide in the original post?

**Comment by doda-mt** [comment]
Experiencing the same issue on a fresh install of SublimeText 3 v3126 @aziz . Surely it can't be too hard to wait for the `view` to be available before accessing it?

**Comment by antenando** [comment]
Same thing with me, folks.

```py
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in check_view_event_listeners
    listeners.append(cls(view))
  File "hyper_click_annotator in /Users/fernandobueno/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 34, in __init__
AttributeError: 'NoneType' object has no attribute 'folders'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 280, in <lambda>
    lambda: check_view_event_listeners(view))
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in check_view_event_listeners
    listeners.append(cls(view))
  File "hyper_click_annotator in /Users/fernandobueno/Library/Application Support/Sublime Text 3/Installed Packages/HyperClick.sublime-package", line 34, in __init__
AttributeError: 'NoneType' object has no attribute 'folders'
```

**Comment by antenando** [comment]
Still no help for this ?

**Comment by aziz** [comment]
I think I've fixed the issue. feel free to reopen it if you still have problems
